export const propertiesI = [
   {
      "description": "A estrenar, a 5 min. del centro caminando, con áreas comunes, sin problemas de estacionamiento. 6 departamentos tipo loft, 1 recámara, sala, estancia, cocina, baño, bodega, 1 cajón de estacionamiento; 2 departamentos con habitación en mezanine.EQUIPAMIENTO:Mini Split, cocina con acabado de chapa de encino, cubierta de granito y parrilla de acero.AMENIDADES:Área de convivencia, solario en nivel superior con salas tipo lounge, ambientada con agradables luces de acento, con opción a utilizarla como terraza, equipada con asadores y un jardín para mascotas.PRECIOS$ 1,578,115.00 hasta $ 2,360,236MEDIDASDe 45 m2 hasta 68 m2",
      "colonia": "Zona Centro",
      "price": "1578115 ",
      "operacion": "Venta",
      "claveEB": "EB-IR6940",
      "urlImage": "https://assets.easybroker.com/property_images/2526940/39449039/EB-IR6940.jpg?version=1634060993",
      "urlProp": "https://www.matchhome.net/property/departamentos-en-venta-en-torre-11-en-el-centro-de-la-ciudad",
      "beds": "1",
      "bathroom": "1",
      "park": "1",
      "areaBuilding": "45",
      "flors": "1",
      "agent": "Enrique Marines"
   },
   {
      "description": "Departamentos de lujo, céntricos, con 2 elevadores, escaleras de uso cotidiano y escalera de emergencia.Con 2 recámaras, baño completo, cocina, comedor, sala -estancia, área de lavado.MEDIDAS72.43 m2 totales65.59 m2 interior6.84 m2 balcón.",
      "colonia": "San Felipe I",
      "price": "2666742 ",
      "operacion": "Venta",
      "claveEB": "EB-IK7885",
      "urlImage": "https://assets.easybroker.com/property_images/2457885/38283901/EB-IK7885.jpg?version=1631125634",
      "urlProp": "https://www.matchhome.net/property/departamento-en-san-felipe-san-felipe-i",
      "beds": "2",
      "bathroom": "1",
      "park": "2",
      "areaBuilding": "72",
      "flors": "4",
      "agent": "Enrique Marines"
   },
   {
      "description": "Cerca del Periférico de la Juventud , con vías de acceso rápidas , cerca de hosítales, escuelas y centros comerciales, totalmente equipada.Planta baja:Sala, comedor, cocina integral, lavandería, medio baño, bonito patio con terraza , pasillo de servicio, cochera techada 2 autos.Planta Alta:Recamara principal con baño y vestidor, 2 recamaras comparten baño, estancia.Equipamiento :Cocina integral y lavabos en encino y granito, aire acondicionado, calefacción, 2 tinacos con hidroneumático, boiler, tanque estacionario, ventanearía doble vidrio, barandales y canceles de baño en cristal templado, porcelanatos.",
      "colonia": "Lomas Universidad IV",
      "price": "3350000 ",
      "operacion": "Venta",
      "claveEB": "EB-HN1547",
      "urlImage": "https://assets.easybroker.com/property_images/2221547/34240041/EB-HN1547.jpg?version=1621039190",
      "urlProp": "https://www.matchhome.net/property/casa-en-venta-en-lomas-universidad-lomas-universidad-iv-chihuahua",
      "beds": "3",
      "bathroom": "2",
      "halfBathroom": "1",
      "park": "2",
      "areaBuilding": "260",
      "areaTotal": "222",
      "flors": "2",
      "agent": "Enrique Marines"
   },
   {
      "description": "En avenida de mucho tráfico, para oficina o casas en el centro de la ciudad.",
      "colonia": "Zona Centro",
      "price": "2200000 ",
      "operacion": "Venta",
      "claveEB": "EB-HH2575",
      "urlImage": "https://assets.easybroker.com/property_images/2162575/33231793/EB-HH2575.jpg?version=1618521238",
      "urlProp": "https://www.matchhome.net/property/casa-en-venta-en-av-principal-para-casa-u-oficina-excelente-ubicacion",
      "beds": "3",
      "bathroom": "1",
      "halfBathroom": "1",
      "park": "1",
      "areaBuilding": "164",
      "areaTotal": "82",
      "agent": "Enrique Marines"
   },
   {
      "description": "LA GRAN PIRÁMIDE, VENTA DE INMUEBLE OPCION TRASPASO DEL NEGOCIO.LIDERES EN SU RAMO.INCLUYE NOMBRE E INVENTARIO.INMUEBLE DE 490 m2 DE SUPERFICIE MAS MEZANNINE CON OFICINAS Y PRIVADOS DE 124 M2.TERRENO DE 490 M2.PRECIO TOTAL DEL NEGOCIO (NOMBRE, INVENTARIOS E INMUEBLE) $ 6,000,000.PRECIO SÓLO DEL INMUEBLE $ 3,600,000.EQUIPO:AIRE ACONDICIONADOCALEFACCIONTANQUE ESTACIONARIOSUB ESTACIÓNCOLCHA AISLANTE EN TECHOBAÑOS ÁREA PUBLICO.",
      "colonia": "Zona Centro",
      "price": "3600000 ",
      "operacion": "Venta",
      "claveEB": "EB-HM8063",
      "urlImage": "https://assets.easybroker.com/property_images/2218063/34179789/EB-HM8063.jpg?version=1620930087",
      "urlProp": "https://www.matchhome.net/property/la-gran-piramide-venta-de-negocio-con-opcion-a-traspaso",
      "bathroom": "2",
      "park": "3",
      "areaBuilding": "614",
      "flors": "1",
      "agent": "Enrique Marines"
   },
   {
      "description": "En fracc. privado , de mucha plusvalía , con vías de acceso rápidas .La casa consta de :PLANTA BAJA : recibidor , 1/2 baño con granito y espejo , sala ,comedor,cocina con granito y desayunador , lavandería ,cochera para 2 autos ,escalera de cristal templado, preparación para cuarto de servicio, jardín, terraza con cantera.PLANTA ALTA: Estancia, closet de blancos , recámara principal con duela , baño y vestidor , cubierta de granito,cancel y espejo.2 recámaras individuales con baño completo y cubiertas de granito.EQUIPAMIENTO: ladrillo térmico, acabado de fachada en recinto, escalones de acceso de cantera , piso de porcelanto importado ,ventanería de doble vidrio , llaves y muebles de baños importados, 2 equipos de aire acondicionado y calefacción , tanque estacionario de 500 lts. ,aljibe con hidroneumático , boiler, riego automatizado , carpintería de encino , cocina integral con granito ,cochera eléctrica de herrería, impermeabilizada .",
      "colonia": "Pedregal de San Ángel",
      "price": "5950000 ",
      "operacion": "Venta",
      "claveEB": "EB-GY0449",
      "urlImage": "https://assets.easybroker.com/property_images/2070449/31775297/EB-GY0449.jpg?version=1614886308",
      "urlProp": "https://www.matchhome.net/property/casa-en-venta-en-pedregal-del-angel",
      "beds": "3",
      "bathroom": "3",
      "halfBathroom": "1",
      "park": "2",
      "areaBuilding": "300",
      "areaTotal": "306",
      "agent": "Enrique Marines"
   },
   {
      "description": "Edificio con departamentos de lujo, cerca de las principales plazas, centros comerciales y hospitales, cerca de la universidad la Salle y del parque el Rejón.Con vistas privilegiadas, con estacionamiento seguro y exclusivo, vías de acceso controladas.Accesibilidad para personas con discapacidad y adultos mayores, con vía libre al elevador, acceso desde la calle y el estacionamiento.Están hechos con aislamiento termo-acústico.Cada departamento tiene su propia bodega.AMENIDADESÁrea común con asadores y área de descanso.MEDIDASDE 57 m2 a 59 m2 , en diferentes pisos.PRECIODe $ 2109,523. hasta $ 2342,377.",
      "colonia": "Lomas Altas I",
      "price": "2109523 ",
      "operacion": "Venta",
      "claveEB": "EB-IK0276",
      "urlImage": "https://assets.easybroker.com/property_images/2450276/38147920/EB-IK0276.jpg?version=1630713668",
      "urlProp": "https://www.matchhome.net/property/departamentos-en-venta-en-lomas-altas-lomas-altas-i",
      "beds": "1",
      "bathroom": "1",
      "park": "1",
      "areaBuilding": "57.8",
      "agent": "Enrique Marines"
   },
   {
      "description": "Frente a Parque, con fácil acceso.Completamente amueblada , cuenta con cochera techada para 2 autos ,1/2 baño , sala, comedor, recámara en planata baja ,con bañoy vestidor , cocina con encimeras de Cuarzo , campana,estufa,reffrigerador,microondas .2 recámaras secundarias con walk-in closet y baño compartido con doble lavabo . Áreas de lavandería , recámara principal con baño y doble regadera, 2 lavabos y sanitario , todo separado.EQUIPAMIENTO :Boiler ,hidroneumático, tanque de gas de 500 lts, 2 master cool , 2 calefacciones, se queda con persianas dobles de primera calidad, algunos candiles y ábanicos.SE VENDE AMUEBLADA",
      "colonia": "Bosques del Valle",
      "price": "5200000 ",
      "operacion": "Venta",
      "claveEB": "EB-GV8030",
      "urlImage": "https://assets.easybroker.com/property_images/2048030/31406116/EB-GV8030.jpg?version=1614032579",
      "urlProp": "https://www.matchhome.net/property/casa-en-venta-en-bosques-del-valle-040b2195-1082-43de-8d17-72f5ea956242",
      "beds": "4",
      "bathroom": "3",
      "halfBathroom": "1",
      "park": "2",
      "areaBuilding": "302",
      "areaTotal": "250",
      "agent": "Enrique Marines"
   },
   {
      "description": "En Uno de los Fracc. Más Exclusivos y con La Mejor Vista al Campo de Golf . Cerca del Periférico de la Juventud , Fácil Acceso , Cerca de Escuelas , Hospitales y Centros Comerciales.",
      "colonia": "Bosques de San Francisco I y II",
      "price": "6707456 ",
      "operacion": "Venta",
      "claveEB": "EB-FN3795",
      "urlImage": "https://assets.easybroker.com/property_images/1703795/25766660/EB-FN3795.jpg?version=1597513619",
      "urlProp": "https://www.matchhome.net/property/terreno-en-venta-en-bosques-de-san-francisco-ac1df7eb-f250-4ca7-b381-e7d03a6e8894",
      "areaTotal": "598",
      "agent": "Enrique Marines"
   },
   {
      "description": "En una de las mejores zonas para vivir , con fácil acceso , con alberca y frente a parque.Planta BajaSala, comedor, cocina integral, desayunador, lavandería, patio amplio con jardines, palapa con barra y asador, jardín frontal y amplia cochera techada para 3 autos.Planta Alta4 recamaras (principal con baño, jacuzzi y vestidor) baño compartido, estancia.EQUIPAMIENTO :Cocina integral, closets, jacuzzi, aire acondicionado, 2 mini splits, calefacción, aljibe, hidro neumático, boiler, alberca equipada, tanque estacionario, cochera eléctrica, ventanería doble vidrio, persianas, shooters, abanicos, candilería, pisos en cerámica y duela.Superficie.",
      "colonia": "Lomas del Valle I y II",
      "price": "8800000 ",
      "operacion": "Venta",
      "claveEB": "EB-GW5247",
      "urlImage": "https://assets.easybroker.com/property_images/2055247/31522440/EB-GW5247.jpg?version=1614280673",
      "urlProp": "https://www.matchhome.net/property/casa-en-venta-en-lomas-del-valle-con-alberca",
      "beds": "4",
      "bathroom": "2",
      "halfBathroom": "1",
      "park": "3",
      "areaBuilding": "463",
      "areaTotal": "520",
      "flors": "2",
      "agent": "Enrique Marines"
   },
   {
      "description": "Excelente Terreno Comercial . ( Jardín Corona ) , Ave. Teofilo Borunda y Ave. Cristobal Colón.T 8930. m2C 640 m2$ 51,347,500$ de Renta $ 280,000  iva",
      "colonia": "Zona Centro",
      "price": "51347500 ",
      "operacion": "Venta",
      "claveEB": "EB-EA6990",
      "urlImage": "https://assets.easybroker.com/property_images/1316990/19639310/EB-EA6990.jpeg?version=1572553188",
      "urlProp": "https://www.matchhome.net/property/terreno-en-venta-excelente-punto-jardin-corona",
      "areaTotal": "8,930",
      "agent": "Enrique Marines"
   },
   {
      "description": "En Fracc. privado, cerca de escuelas, universidades, centros comerciales y restaurantes.CONSTA DE :PLANTA BAJA:Cochera para 2 autos, sala, comedor, cocina, lavandería, 1/2 baño, patio y pasillo de servicio.PLANTA ALTA:Estancia, recámara principal con closet y baño, 2 recámaras secundarias que comparten baño.EQUIPAMIENTO:Cocina integral, estufa, campana, aire acondicionado, boiler, tinaco e hidroneumático.",
      "colonia": "Puente de Piedra",
      "price": "2150000 ",
      "operacion": "Venta",
      "claveEB": "EB-JD8318",
      "urlImage": "https://assets.easybroker.com/property_images/2648318/41517598/EB-JD8318.jpg?version=1639165055",
      "urlProp": "https://www.matchhome.net/property/casa-en-venta-en-puente-de-piedra-por-las-canteras",
      "beds": "3",
      "bathroom": "2",
      "halfBathroom": "1",
      "park": "2",
      "areaBuilding": "180",
      "areaTotal": "120",
      "agent": "Enrique Marines"
   },
   {
      "description": "Con fácil acceso , a 5 min. del Periférico de la Juventud, cerca de hospitales, centros comerciales, colegios ,universidades y casinos.CONSTA DE:Sala, comedor, cocina integral, área de lavado, estancia, área de bar, 2 recámaras con baño completo y vestidor, balcón, bodega y 2 estacionamientos.AMENIDADES:Alberca, gimnasio, jardín con asador y juegos, terraza también con asador, sala y bar, espacio para fiestas, acceso controlado.MEDIDASConstrucción 171 m2Terraza 9 m2Bodega 5 m22 cajones deestacionamiento 29 m2",
      "colonia": "Barrancas",
      "price": "6200000 ",
      "operacion": "Venta",
      "claveEB": "EB-IR4286",
      "urlImage": "https://assets.easybroker.com/property_images/2524286/39405828/EB-IR4286.jpg?version=1633979209",
      "urlProp": "https://www.matchhome.net/property/departamento-de-lujo-en-torre-cenit-en-el-mejor-lugar",
      "beds": "2",
      "bathroom": "2",
      "park": "2",
      "areaBuilding": "171",
      "agent": "Enrique Marines"
   },
   {
      "description": "Hermosa casa céntrica, muy cerca de la UACH, de una sola planta, en esquina.CONSTA DE:4 recámaras ( principal con baño y vestidor).4.5 baños.Sala - Comedor.Comedor.Cocina.Lavandería.2 estancias.Patio.Cuarto de servicio.Jardín al frente y atrás.EQUIPAMIENTO:Cocina integral.Closets.Hidroneumático.Aljibe.Pisos de Cerámica.Preparación para aire acondicionado y calefacción.Cochera eléctrica.Barandales y rejas.4 mezanineAlacena en cocina y para blancos.",
      "colonia": "San Felipe II",
      "price": "7800000 ",
      "operacion": "Venta",
      "claveEB": "EB-IP2107",
      "urlImage": "https://assets.easybroker.com/property_images/2502107/39046941/EB-IP2107.jpg?version=1633021150",
      "urlProp": "https://www.matchhome.net/property/casa-en-venta-en-san-felipe-con-alberca-techada",
      "beds": "4",
      "bathroom": "4",
      "halfBathroom": "1",
      "park": "4",
      "areaBuilding": "508",
      "areaTotal": "728",
      "flors": "1",
      "agent": "Enrique Marines"
   },
   {
      "description": "Céntrica, muy cerca de centros comerciales, escuelas y avenidas principales. Muy amplia.CONSTA DE:Sala-comedor, comedor, cocina, estancia, patio y cochera para 1 auto.EQUIPAMIENTO:Cocina integral, closets, pisos de cerámica, aire acondicionado, boiler, cochera eléctrica, barandales y tanque estacionario.",
      "colonia": "Las Granjas",
      "price": "1300000 ",
      "operacion": "Venta",
      "claveEB": "EB-IN0471",
      "urlImage": "https://assets.easybroker.com/property_images/2480471/38667479/EB-IN0471.jpg?version=1632182597",
      "urlProp": "https://www.matchhome.net/property/casa-en-venta-en-las-granjas-de-2-niveles",
      "beds": "3",
      "bathroom": "2",
      "park": "1",
      "areaBuilding": "182",
      "areaTotal": "115",
      "flors": "1",
      "agent": "Enrique Marines"
   },
   {
      "description": "En Fracc. privado, frente a parque, con patio amplio, nueva, con acabados de lujo, patio amplio, todas las recamaras tienen vestidor y baño.Equipamiento:Cocina integral, closets, aire acondicionado, calefacción, hidroneumático, aljibe y ventaneria de doble cristal, cochera eléctrica y jardín. MCBVAL06",
      "colonia": "Bosques del Valle",
      "price": "4700000 ",
      "operacion": "Venta",
      "claveEB": "EB-CM0602",
      "urlImage": "https://assets.easybroker.com/property_images/910602/36093592/EB-CM0602.jpg?version=1625703691",
      "urlProp": "https://www.matchhome.net/property/casa-en-venta-en-bosques-del-valle-por-la-zona-de-las-cantras",
      "beds": "3",
      "bathroom": "3",
      "halfBathroom": "1",
      "park": "2",
      "areaBuilding": "245",
      "areaTotal": "290",
      "flors": "2",
      "agent": "Enrique Marines"
   },
   {
      "description": "En plaza comercial, con gran afluencia vehicular, cerca de universidades, colegios y plazas comerciales. A 5 minutos del Parque el Reliz.Con mezanine de 44 m2",
      "colonia": "Cerrada Castilla",
      "price": "3439372 ",
      "operacion": "Venta",
      "claveEB": "EB-IC2730",
      "urlImage": "https://assets.easybroker.com/property_images/2372730/36858425/EB-IC2730.jpg?version=1627582912",
      "urlProp": "https://www.matchhome.net/property/local-en-venta-por-el-reliz",
      "park": "6",
      "areaBuilding": "84",
      "agent": "Enrique Marines"
   },
   {
      "description": "Departamentos de lujo, céntricos, cerca de la UACH, a 5 min de la deportiva. Con 2 elevadores, escaleras de uso cotidiano y escalera de emergencia.CONSTA DE:* 1 recámara* 1 baño completo* 1 estacionamientoCon sala/ estancia , cocina, comedor y área de lavado.MEDIDAS68.98 m2 totales62.14 m2 interior6.84 m2 balcón",
      "colonia": "San Felipe II",
      "price": "2538337 ",
      "operacion": "Venta",
      "claveEB": "EB-IK7949",
      "urlImage": "https://assets.easybroker.com/property_images/2457949/38285276/EB-IK7949.jpg?version=1631126972",
      "urlProp": "https://www.matchhome.net/property/departamentos-de-lujo-en-san-felipe",
      "beds": "1",
      "bathroom": "1",
      "park": "1",
      "areaBuilding": "68.98",
      "flors": "2",
      "agent": "Enrique Marines"
   }
]